# Wire-to-trade capstone
#
#   make          optimised build      -> build/release/
#   make asan     ASan + UBSan         -> build/asan/
#   make tsan     ThreadSanitizer      -> build/tsan/
#   make all      release + asan
#   make test     build tests/test_*.cpp under ASan + UBSan and run them
#   make clean    remove build/
#
# Each configuration writes to its own directory, so they never clobber each
# other and you can run either without triggering a rebuild. ASan and TSan
# cannot be combined in one binary, hence three targets rather than two.

CXX  := clang++
STD  := c++20
WARN := -Wall -Wextra -Wpedantic
BASE := -std=$(STD) $(WARN) -MMD -MP

# -fno-sanitize-recover=all makes UBSan abort instead of printing and carrying
# on. Without it a UB report scrolls past and the run still exits 0.
RELEASE_FLAGS := $(BASE) -O2 -g
ASAN_FLAGS    := $(BASE) -O1 -g -fno-omit-frame-pointer \
                 -fsanitize=address,undefined -fno-sanitize-recover=all
TSAN_FLAGS    := $(BASE) -O1 -g -fno-omit-frame-pointer -fsanitize=thread

SRC   := src
BUILD := build
PROGS := consumer producer probe

# Tests: every tests/test_*.cpp becomes its own GoogleTest binary, built with
# the ASan + UBSan flags so each test run is also a sanitizer run.
# GoogleTest comes from `brew install googletest`. On Linux, install the distro
# package and run `make test GTEST_PREFIX=/usr`.
TESTS        := tests
GTEST_PREFIX ?= /opt/homebrew/opt/googletest
GTEST_CFLAGS := -isystem $(GTEST_PREFIX)/include
GTEST_LIBS   := -L$(GTEST_PREFIX)/lib -lgtest -lgtest_main
TEST_SRCS    := $(wildcard $(TESTS)/test_*.cpp)
TEST_BINS    := $(patsubst $(TESTS)/%.cpp,$(BUILD)/test/%,$(TEST_SRCS))

RELEASE_BINS := $(addprefix $(BUILD)/release/,$(PROGS))
ASAN_BINS    := $(addprefix $(BUILD)/asan/,$(PROGS))
TSAN_BINS    := $(addprefix $(BUILD)/tsan/,$(PROGS))

.DEFAULT_GOAL := release

release: $(RELEASE_BINS)
asan:    $(ASAN_BINS)
tsan:    $(TSAN_BINS)
all:     release asan

$(BUILD)/release/%: $(SRC)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(RELEASE_FLAGS) $< -o $@

$(BUILD)/asan/%: $(SRC)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(ASAN_FLAGS) $< -o $@

$(BUILD)/tsan/%: $(SRC)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(TSAN_FLAGS) $< -o $@

test: $(TEST_BINS)
	@for t in $(TEST_BINS); do echo "== $$t"; ./$$t || exit 1; done

$(BUILD)/test/%: $(TESTS)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(ASAN_FLAGS) -I$(SRC) $(GTEST_CFLAGS) $< -o $@ $(GTEST_LIBS)

clean:
	rm -rf $(BUILD)

# Header dependencies, generated by -MMD -MP. Matters from Phase 2 onward when
# there are headers to depend on.
-include $(shell find $(BUILD) -name '*.d' 2>/dev/null)

.PHONY: release asan tsan all test clean
