# Wire-to-trade capstone
#
#   make          optimised build      -> build/release/
#   make asan     ASan + UBSan         -> build/asan/
#   make tsan     ThreadSanitizer      -> build/tsan/
#   make all      release + asan
#   make clean    remove build/
#
# Each configuration writes to its own directory, so they never clobber each
# other and you can run either without triggering a rebuild. ASan and TSan
# cannot be combined in one binary, hence three targets rather than two.

CXX  := clang++
STD  := c++20
WARN := -Wall -Wextra -Wpedantic
BASE := -std=$(STD) $(WARN) -MMD -MP

# -fno-sanitize-recover=all makes UBSan abort instead of printing and carrying
# on. Without it a UB report scrolls past and the run still exits 0.
RELEASE_FLAGS := $(BASE) -O2 -g
ASAN_FLAGS    := $(BASE) -O1 -g -fno-omit-frame-pointer \
                 -fsanitize=address,undefined -fno-sanitize-recover=all
TSAN_FLAGS    := $(BASE) -O1 -g -fno-omit-frame-pointer -fsanitize=thread

SRC   := src
BUILD := build
PROGS := consumer producer

RELEASE_BINS := $(addprefix $(BUILD)/release/,$(PROGS))
ASAN_BINS    := $(addprefix $(BUILD)/asan/,$(PROGS))
TSAN_BINS    := $(addprefix $(BUILD)/tsan/,$(PROGS))

.DEFAULT_GOAL := release

release: $(RELEASE_BINS)
asan:    $(ASAN_BINS)
tsan:    $(TSAN_BINS)
all:     release asan

$(BUILD)/release/%: $(SRC)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(RELEASE_FLAGS) $< -o $@

$(BUILD)/asan/%: $(SRC)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(ASAN_FLAGS) $< -o $@

$(BUILD)/tsan/%: $(SRC)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(TSAN_FLAGS) $< -o $@

clean:
	rm -rf $(BUILD)

# Header dependencies, generated by -MMD -MP. Matters from Phase 2 onward when
# there are headers to depend on.
-include $(shell find $(BUILD) -name '*.d' 2>/dev/null)

.PHONY: release asan tsan all clean
